# Generated by Django 4.2.3 on 2023-08-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bngjobs',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='eligibility',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='bngjobs',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='eligibility',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hydjobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='eligibility',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='punejobs',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
